### ISSUE TITLE
no module named util_ds

### ISSUE THREAD

**Issue by 18222278799** [Sohone-Guo/Pointer-Generator#2]
您好，这个我用导入数据，nlp.py
里面有个from utils_da.nlp.os import read_folder_content
这个没有no module named util_ds，请问这个模型在哪里，谢谢

**Comment by 18222278799** [comment]
还想问一下您，这个词向量什么用的什么

**Comment by Sohone-Guo** [comment]
1、util_ds 需要进行pip的安装，
2、词向量没有加载预训练模型，由训练集训练而来，
