### ISSUE TITLE
name "result" is not defined

### ISSUE THREAD

**Issue by zhangtianlin** [Sohone-Guo/Pointer-Generator#3]
Hello, i run your programm.
When i exchange the number of batch_size.
it has an error,
Traceback():
    File "....main.py", line 126, in <module>
      with open("test.txt", “a+”， encoding=''utf-8'') as a : a.write("".join(result)+“\n”)
 NameError: name "result" is not defined

i dont know the reason. Thanks

**Comment by Sohone-Guo** [comment]
Didn't... I will check it today.

**Comment by Sohone-Guo** [comment]
The naive dataset just has two news.
It will make an error if the batch size larger than the size of the dataset.

Here is the code:
if input.size(0) != configure["batch_size"]: continue
