### ISSUE TITLE
训练时间和loss

### ISSUE THREAD

**Issue by 18222278799** [Sohone-Guo/Pointer-Generator#4]
您好，请问下您训练时候用了多少数据量，有个微博标题的数据，我用了3w的训练量结果显示CUDNN_ERROE_STATE之类的错误，将缩小到5000才能正常训练，不知道什么原因。
还有您用的什么机器收敛情况是什么样子的，我用了1050Ti，虽说差点，但是跑了一天Loss是800多，我不知道您是否也是这个loss情况。

**Comment by Sohone-Guo** [comment]
不好意思，这个版本是简化的版本，每一个模块都没有复杂化，主要是提供一个易于理解算法的代码，
1：非简化版本，训练时间的话，我用的是titan xp，2万左右的数据，平均文章是300多个字，摘要是30多个字，大概2-3小时，loss趋近于0.5-1之间，就可以了，
2：标题的数据我没有生成过，但是如果标题对文章的内容升华程度较大的话，的确很不好生成，
3：如果只是测试和学习，我觉得我提供的没有问题，但是如果需要使用，还需要进行改进每个部分，

**Comment by phosfuldev** [comment]
@Sohone-Guo 你好，请问非简化版本指的是2017 paper原本的版本吗？这个版本跟“非简化版本”差别有多大呢？

**Comment by Sohone-Guo** [comment]
Hi，功能模块，主要是Copy mechine 在输入端简化了超出词表的输入，所以不能实现算法本身的unk词copy.  还有就是coverage机制，可以解决一定的重复注意问题，

**Comment by phosfuldev** [comment]
@Sohone-Guo 谢谢！
